#!/bin/bash
# check-tailwind.sh — Verify Tailwind.html is up-to-date with output.css
# Strategy: build fresh output.css, generate expected Tailwind.html, diff against existing.
set -euo pipefail

echo "=== Tailwind Consistency Check ==="

# Step 1: Build fresh output.css
echo "Building output.css..."
npm run build-css --silent

if [ ! -f "output.css" ]; then
  echo "FAIL: output.css was not generated by build-css."
  exit 1
fi

# Step 2: Generate expected Tailwind.html content using node
echo "Generating expected Tailwind.html..."
EXPECTED=$(node -e "const fs=require('fs'); const css=fs.readFileSync('output.css','utf8'); process.stdout.write('<style>\n'+css+'\n</style>\n')")

# Step 3: Compare with existing Tailwind.html
if [ ! -f "Tailwind.html" ]; then
  echo "FAIL: Tailwind.html does not exist. Run 'npm run build' to generate it."
  exit 1
fi

ACTUAL=$(cat Tailwind.html)

if [ "$EXPECTED" = "$ACTUAL" ]; then
  echo "OK: Tailwind.html is up-to-date."
  exit 0
else
  echo "FAIL: Tailwind.html is out-of-date or differs from expected output."
  echo "Run 'npm run build' to regenerate."
  echo ""
  echo "--- Diff (expected vs actual) ---"
  diff <(echo "$EXPECTED") <(echo "$ACTUAL") || true
  exit 1
fi
